# Generated by Django 2.2.3 on 2020-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
