# Generated by Django 2.2.3 on 2020-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
